spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: candle-aggregator
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

app:
  topics:
    raw-ticks: raw-ticks
    candles: candles
  stores:
    candle-1m: candle-1m-store
    candle-5m: candle-5m-store
    candle-1h: candle-1h-store