spring:
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: moving-avg-processor
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

app:
  topics:
    candles: candles
    signals: signals
  stores:
    sma: sma-store