spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trading-engine
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8082
        specific.avro.reader: "true"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8082
  datasource:
    url: jdbc:postgresql://localhost:5433/tickerflow
    username: tickerflow
    password: tickerflow
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: trading

app:
  topics:
    signals: signals
    trade-events: trade-events