spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8082
        specific.avro.reader: "true"
  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${MAILGUN_SMTP_USERNAME}
    password: ${MAILGUN_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  topics:
    trade-events: trade-events
  mail:
    from: ${MAILGUN_SMTP_USERNAME}
    to: ${PERSONAL_EMAIL}